In [4]:
import pandas as pd

df = pd.read_csv("C:\\Users\\marka\\Naresh IT\\Dataset\HR_Employee_Dataset - HR_Employee_Dataset.csv")

In [5]:
df

,Employee_ID,Name,Age,Gender,Department,Designation,Salary,Experience_Years,Joining_Date,Performance_Rating
0,EMP2000,Employee_0,42,Male,Marketing,Executive,144857,13.4,2019-06-11,1
1,EMP2001,Employee_1,42,Female,IT,Manager,39738,17.5,2015-10-14,5
2,EMP2002,Employee_2,26,Female,Operations,Executive,30703,15.3,2022-09-05,2
3,EMP2003,Employee_3,41,Male,Operations,Executive,133776,14.7,2018-05-20,5
4,EMP2004,Employee_4,58,Female,HR,Executive,69422,9.9,2019-03-28,5
...,...,...,...,...,...,...,...,...,...,...
495,EMP2495,Employee_495,43,Female,Finance,Manager,143805,9.7,2023-02-06,1
496,EMP2496,Employee_496,54,Female,Marketing,Executive,113846,1.3,2019-10-03,4
497,EMP2497,Employee_497,57,Female,Finance,Executive,42927,14.1,2022-08-21,1
498,EMP2498,Employee_498,44,Male,Marketing,Associate,140589,6.9,2020-05-25,4
499,EMP2499,Employee_499,55,Male,Marketing,Executive,135657,15.0,2020-12-12,1

In [6]:
# 1. How many employees are there in each department?

df.value_counts("Department").reset_index(name = "Employee")

   Department  Employee
0          IT       121
1     Finance       109
2          HR        94
3  Operations        94
4   Marketing        82

In [7]:
df["Department"].value_counts().reset_index(name = "Employee")

   Department  Employee
0          IT       121
1     Finance       109
2  Operations        94
3          HR        94
4   Marketing        82

In [8]:
# 2. What is the gender distribution in the company (percentage)?

df["Gender"].value_counts(normalize = True)*100

Gender
Female    50.6
Male      49.4
Name: proportion, dtype: float64

In [9]:
df["Gender"].value_counts(normalize=True).mul(100).reset_index(name="Percentage")

   Gender  Percentage
0  Female        50.6
1    Male        49.4

In [10]:
# 3. Find the average salary of the company.

df["Salary"].mean()

np.float64(83582.674)

In [11]:
# 4. List employees who are older than 50 years.

df.loc[df["Age"]>50, ["Name","Age"]]

             Name  Age
4      Employee_4   58
6      Employee_6   54
10    Employee_10   56
12    Employee_12   55
14    Employee_14   53
..            ...  ...
488  Employee_488   52
493  Employee_493   59
496  Employee_496   54
497  Employee_497   57
499  Employee_499   55

[125 rows x 2 columns]

In [12]:
# 5. Find employees with performance rating = 5.

df.loc[df["Performance_Rating"]==5, ["Name","Performance_Rating"]]

             Name  Performance_Rating
1      Employee_1                   5
3      Employee_3                   5
4      Employee_4                   5
7      Employee_7                   5
8      Employee_8                   5
..            ...                 ...
477  Employee_477                   5
485  Employee_485                   5
487  Employee_487                   5
489  Employee_489                   5
492  Employee_492                   5

[101 rows x 2 columns]

In [13]:
# 6. Count how many employees joined after 2020.
df["Joining_Date"] = pd.to_datetime(df["Joining_Date"])

In [14]:
df.loc[df["Joining_Date"].dt.year > 2020, ["Name","Joining_Date"]]

             Name Joining_Date
2      Employee_2   2022-09-05
12    Employee_12   2021-09-20
21    Employee_21   2023-01-08
26    Employee_26   2023-02-03
28    Employee_28   2021-05-13
..            ...          ...
489  Employee_489   2021-04-05
491  Employee_491   2021-12-11
492  Employee_492   2021-03-05
495  Employee_495   2023-02-06
497  Employee_497   2022-08-21

[134 rows x 2 columns]

In [15]:
(df["Joining_Date"].dt.year > 2020).sum()

np.int64(134)

In [16]:
# 7. What is the youngest and oldest employee age?

# Youngest Age
df["Age"].min()

22

In [17]:
# Oldest Age

df["Age"].max()

59

In [18]:
# 8. Display top 10 highest-paid employees.

df.sort_values(by="Salary", ascending=False).head(10)[["Name","Salary"]]

             Name  Salary
192  Employee_192  149593
91    Employee_91  149572
213  Employee_213  149036
468  Employee_468  148886
165  Employee_165  148652
423  Employee_423  148447
444  Employee_444  147928
402  Employee_402  147581
75    Employee_75  146503
240  Employee_240  146278

In [19]:
# 9. How many employees are there in each designation?


df["Designation"].value_counts().reset_index(name = "Name")

  Designation  Name
0   Executive   108
1   Associate   103
2        Lead   102
3     Manager    97
4     Analyst    90

In [20]:
# 10. Find average experience of employees in the IT department.

df[df["Department"] == "IT"]["Experience_Years"].mean()

np.float64(9.879338842975207)

### #*MEDIUM LEVEL (Business Logic + Grouping)*

In [21]:
# 1. Find department-wise average salary.


df.groupby("Department")["Salary"].mean().reset_index(name="Average_Salary")

   Department  Average_Salary
0     Finance    82828.073394
1          HR    85806.319149
2          IT    78075.330579
3   Marketing    86696.658537
4  Operations    86606.829787

In [22]:
# 2. Which department has the highest average performance rating?

df.groupby("Department")["Performance_Rating"].mean().sort_values(ascending=False).head(1)

Department
IT    3.016529
Name: Performance_Rating, dtype: float64

In [23]:
# 3. Identify employees whose salary is above company average.

df.loc[df["Salary"]> df["Salary"].mean(),["Name","Salary"]]

             Name  Salary
0      Employee_0  144857
3      Employee_3  133776
5      Employee_5  103106
11    Employee_11   99534
13    Employee_13  118262
..            ...     ...
493  Employee_493  114283
495  Employee_495  143805
496  Employee_496  113846
498  Employee_498  140589
499  Employee_499  135657

[240 rows x 2 columns]

In [24]:
# 4. Create an Age Group column:

#    20–30 → Young

#    31–45 → Mid

#    46+ → Senior
#    Then count employees per age group.

import numpy as np

df["Age_Group"] = np.where(
    (df["Age"] >= 20) & (df["Age"] <= 30), "Young",
    np.where(
        (df["Age"] >= 31) & (df["Age"] <= 45), "Mid",
        "Senior"
    )
)


df["Age_Group"].value_counts()

Age_Group
Mid       206
Senior    184
Young     110
Name: count, dtype: int64

In [25]:
def age_group(age):
    if 20 <= age <= 30:
        return "Young"
    elif 31 <= age <= 45:
        return "Mid"
    else:
        return "Senior"

df["Age_Group"] = df["Age"].apply(age_group)

In [26]:
df.value_counts("Age_Group")

Age_Group
Mid       206
Senior    184
Young     110
Name: count, dtype: int64

## .

In [27]:
# 5. Find employees whose experience is greater than department average experience.

df.loc[ df["Experience_Years"] > df.groupby("Department")["Experience_Years"].transform("mean"), ["Name", "Department", "Experience_Years"] ]

             Name  Department  Experience_Years
0      Employee_0   Marketing              13.4
1      Employee_1          IT              17.5
2      Employee_2  Operations              15.3
3      Employee_3  Operations              14.7
5      Employee_5          HR              14.0
..            ...         ...               ...
485  Employee_485  Operations              18.8
488  Employee_488  Operations              13.3
493  Employee_493     Finance              16.6
497  Employee_497     Finance              14.1
499  Employee_499   Marketing              15.0

[248 rows x 3 columns]

In [28]:
df.loc[df["Experience_Years"]> df["Experience_Years"].mean(), ["Name", "Department", "Experience_Years"]]

             Name  Department  Experience_Years
0      Employee_0   Marketing              13.4
1      Employee_1          IT              17.5
2      Employee_2  Operations              15.3
3      Employee_3  Operations              14.7
5      Employee_5          HR              14.0
..            ...         ...               ...
485  Employee_485  Operations              18.8
488  Employee_488  Operations              13.3
493  Employee_493     Finance              16.6
497  Employee_497     Finance              14.1
499  Employee_499   Marketing              15.0

[252 rows x 3 columns]

In [29]:
# 6. Calculate salary growth ratio:
#    Salary / Experience\_Years
#    Find top 10 employees with highest ratio.

df["Salary_Growth_Ratio"] = df["Salary"] / df["Experience_Years"]

In [30]:
df.sort_values(by="Salary_Growth_Ratio", ascending=False).head(10)

,Employee_ID,Name,Age,Gender,Department,Designation,Salary,Experience_Years,Joining_Date,Performance_Rating,Age_Group,Salary_Growth_Ratio
329,EMP2329,Employee_329,57,Male,Operations,Analyst,136452,0.7,2017-08-09,2,Senior,194931.428571
375,EMP2375,Employee_375,44,Male,IT,Executive,117512,0.7,2017-02-21,5,Mid,167874.285714
387,EMP2387,Employee_387,43,Male,HR,Associate,97853,0.6,2019-02-10,4,Mid,163088.333333
454,EMP2454,Employee_454,46,Female,IT,Executive,116131,0.8,2023-01-18,2,Senior,145163.750000
57,EMP2057,Employee_57,22,Female,IT,Manager,144997,1.0,2021-08-24,2,Young,144997.000000
103,EMP2103,Employee_103,54,Male,Operations,Associate,143239,1.0,2018-02-23,5,Senior,143239.000000
86,EMP2086,Employee_86,33,Female,IT,Lead,120356,0.9,2022-02-18,5,Mid,133728.888889
82,EMP2082,Employee_82,40,Male,IT,Associate,75798,0.6,2022-10-10,3,Mid,126330.000000
336,EMP2336,Employee_336,29,Female,Operations,Executive,98270,0.8,2018-08-03,3,Young,122837.500000
118,EMP2118,Employee_118,34,Male,Marketing,Analyst,115676,1.0,2020-12-16,5,Mid,115676.000000

In [33]:
df["Age"].mean() * 100

np.float64(4101.2)