In [254]:
import pandas as pd

In [255]:
df = pd.read_csv("C:\\Users\\marka\\Naresh IT\\Dataset\Pandas_Practice_Dataset.xlsx - Messy_Dataset.csv")

In [256]:
# Q1. Load the dataset into a Pandas DataFrame and display the first 10 rows.
df.head(n=10)

,Customer_ID,Name,Age,Gender,City,Salary,Experience,Department,Joining_Date,Performance_Score,Loan_Status,Rating
0,1,Amit,43,Female,Chennai,48886,26.0,NaN,02/09/2022,90.81,N,4.5
1,2,Kiran,35,F,Bengaluru,"₹75,196",14.0,NaN,04/01/2023,70.98,NaN,3.5
2,3,Neha,44,M,NaN,111831,28.0,IT,23-Jun-2023,65.04,NaN,-2.0
3,79,Sneha,38,F,HYD,72973,3.0,HR,2021-01-04,65.51,no,1.4
4,5,Rohit,46,F,hyd,64961,17.0,hr,28/03/2018,98.68,Yes,12.0
5,6,Pooja,28,F,Delhi,38199,27.0,hr,19-Mar-2020,96.75,no,1.9
6,7,Neha,59,Female,Bangalore,31152,27.0,NaN,31/12/2020,68.06,No,4.4
7,8,NaN,22,M,Chennai,"₹58,457",5.0,it,2024-10-06,96.17,N,2.7
8,9,Pooja,-5,Unknown,NaN,93372,5.0,Finance,07/12/2020,79.14,Yes,4.0
9,10,Kiran,58,F,NaN,59378,17.0,IT,11-Apr-2020,98.43,Yes,2.5

In [257]:
# Q2. Display the last 10 rows and randomly sample 15 rows.

df.tail(n = 10)

,Customer_ID,Name,Age,Gender,City,Salary,Experience,Department,Joining_Date,Performance_Score,Loan_Status,Rating
990,991,Amit,25,NaN,Bengaluru,80770,20.0,Sales,03-Aug-2022,NaN,N,3.5
991,992,Kiran,38,NaN,NaN,27642,10.0,Finance,09-18-2019,85.19,Yes,3.9
992,993,Arjun,55,NaN,HYD,113515,9.0,it,31/01/2023,50.36,Y,12.0
993,994,Neha,34,F,Bangalore,98950,8.0,Finance,03-28-2023,42.06,Yes,2.1
994,995,Ravi,50,Unknown,Hyderabad,113924,18.0,it,25/01/2021,82.53,Yes,2.3
995,996,Kiran,57,Male,Hyderabad,105886,12.0,IT,2019-08-15,40.16,no,4.3
996,22,Amit,36,Male,NaN,41273,27.0,hr,11-23-2022,65.87,NaN,1.5
997,998,Ravi,22,Unknown,Bangalore,85273,0.0,Sales,04-Mar-2023,50.90,Yes,1.6
998,999,Rohit,21,F,Mumbai,78945,13.0,hr,2021-11-16,61.89,No,3.8
999,1000,Rahul,52,Male,Chennai,66489,26.0,hr,05-Oct-2021,98.59,no,1.8

In [258]:
# Q3. Find:
# • Number of rows
# • Number of columns
# • Column names
# • Data types of each column


# • Column names

print("Columns Name: ",df.columns.tolist())

Columns Name:  ['Customer_ID', 'Name', 'Age', 'Gender', 'City', 'Salary', 'Experience', 'Department', 'Joining_Date', 'Performance_Score', 'Loan_Status', 'Rating']

In [259]:
# • Number of rows

print("Rows: ",df.shape[0])

Rows:  1000

In [260]:
# • Number of columns

print("All Columns: ",df.shape[1])

All Columns:  12

In [261]:
# • Data types of each column

print("Data Types: ")
print("_"*30)
print(df.dtypes)

Data Types:
______________________________
Customer_ID            int64
Name                  object
Age                   object
Gender                object
City                  object
Salary                object
Experience           float64
Department            object
Joining_Date          object
Performance_Score    float64
Loan_Status           object
Rating               float64
dtype: object

In [262]:
# Q4. Find the total number of missing values in each column.


print("Missing Values: ")
print("_"*30,"\n")
print(df.isnull().sum())

Missing Values:
______________________________

Customer_ID            0
Name                  49
Age                    4
Gender               163
City                 104
Salary                46
Experience            17
Department            98
Joining_Date           0
Performance_Score     12
Loan_Status          123
Rating                 7
dtype: int64

In [263]:
# Q5. Display only the rows where Name is missing.

df[df['Name'].isnull()]

,Customer_ID,Name,Age,Gender,City,Salary,Experience,Department,Joining_Date,Performance_Score,Loan_Status,Rating
7,8,NaN,22,M,Chennai,"₹58,457",5.0,it,2024-10-06,96.17,N,2.7
25,26,NaN,35,Female,Hyderabad,NaN,12.0,hr,2020-06-11,88.03,N,1.0
44,45,NaN,59,NaN,Mumbai,"₹117,161",25.0,HR,04-09-2018,93.75,N,4.0
77,78,NaN,21,Unknown,Hyderabad,84654,28.0,IT,11-24-2019,59.43,yes,2.0
87,88,NaN,49,F,HYD,102523,3.0,Marketing,10/06/2019,74.38,N,4.3
92,93,NaN,47,Male,Chennai,98496,5.0,HR,19-Sep-2022,49.10,N,3.3
105,106,NaN,23,Unknown,Bangalore,116217,18.0,Marketing,11/11/2023,67.20,Yes,1.4
121,122,NaN,42,F,Chennai,"₹29,364",8.0,hr,15-Mar-2021,63.66,yes,5.0
135,136,NaN,34,NaN,Pune,38550,9.0,Marketing,2018-07-07,78.62,Y,2.0
148,149,NaN,59,NaN,Hyderabad,45306,16.0,Finance,08-27-2021,70.99,No,3.2
162,163,NaN,58,Unknown,Delhi,54426,28.0,Finance,02/10/2021,52.99,no,2.5
193,194,NaN,57,NaN,Mumbai,39483,29.0,HR,20/02/2022,65.36,Yes,1.8
204,205,NaN,36,F,Delhi,109007,19.0,it,30/07/2021,94.99,yes,2.5
244,245,NaN,50,Male,Pune,70713,26.0,HR,18-Sep-2021,50.72,no,4.3
251,252,NaN,58,Unknown,HYD,105102,0.0,it,20/05/2022,93.16,no,3.7
276,277,NaN,52,Female,Chennai,99886,22.0,HR,2020-10-11,94.11,yes,4.4
283,284,NaN,29,Unknown,hyd,71818,21.0,HR,24/06/2020,55.40,no,1.8
324,325,NaN,59,Male,NaN,98397,25.0,it,28/06/2022,45.52,Y,1.8
325,326,NaN,-5,Unknown,HYD,34077,10.0,hr,2024-08-02,86.08,NaN,1.0
347,348,NaN,29,Unknown,Delhi,90507,19.0,NaN,2019-08-01,82.45,no,4.5
378,379,NaN,24,Unknown,Hyderabad,65126,3.0,HR,17/12/2022,72.08,Y,3.9
381,35,NaN,49,F,Hyderabad,"₹115,289",12.0,Finance,2024-03-29,43.43,No,1.0
433,434,NaN,20,F,hyd,43020,5.0,HR,24-Aug-2022,83.03,Yes,2.5
442,443,NaN,24,M,hyd,79952,11.0,hr,02/01/2024,58.39,Y,4.9
459,460,NaN,27,NaN,HYD,"₹88,749",24.0,IT,13-Feb-2019,42.18,NaN,4.8
463,464,NaN,26,M,hyd,73537,25.0,it,30/03/2024,88.77,NaN,4.3
507,508,NaN,45,Female,Hyderabad,51794,19.0,HR,06-Oct-2019,56.17,NaN,2.2
531,532,NaN,37,M,Bangalore,105345,14.0,it,14-Nov-2018,90.20,Yes,4.1
537,538,NaN,28,Female,Hyderabad,"₹118,577",11.0,Finance,2024-06-30,40.09,N,2.3
584,585,NaN,36,F,Delhi,"₹56,108",18.0,Sales,2020-07-16,55.56,Y,2.2
590,591,NaN,42,Unknown,Pune,44818,9.0,hr,21/11/2019,110.00,N,2.4
606,607,NaN,42,Male,Hyderabad,53655,19.0,Finance,2020-06-28,51.67,Yes,1.3
614,615,NaN,23,Female,Hyderabad,46549,29.0,hr,08/02/2020,50.38,Y,4.4
624,625,NaN,22,Male,hyd,64185,6.0,Marketing,04/12/2020,53.27,N,1.4
655,656,NaN,29,Female,Bangalore,99899,13.0,it,17-Dec-2020,85.51,Y,4.1
666,667,NaN,25,Unknown,hyd,33318,28.0,HR,16-Feb-2023,69.42,Y,3.2
689,690,NaN,44,Female,Hyderabad,"₹88,908",18.0,Finance,18/03/2019,94.23,Yes,2.7
763,764,NaN,31,F,Chennai,75211,23.0,HR,22-Jul-2024,43.20,Yes,3.9
798,799,NaN,49,Unknown,NaN,NaN,12.0,Finance,06-Oct-2023,58.93,No,2.5
832,833,NaN,52,Unknown,Chennai,87562,2.0,Marketing,12/03/2020,55.57,Yes,1.1
863,864,NaN,60,Female,HYD,"₹91,021",17.0,IT,2020-08-14,94.24,Y,1.6
889,890,NaN,NaN,Female,HYD,61284,17.0,Marketing,2018-09-17,68.70,N,2.3
894,895,NaN,42,F,Bangalore,56962,30.0,Finance,09-19-2023,53.43,NaN,3.9
926,927,NaN,22,Unknown,HYD,47210,27.0,hr,07-26-2018,91.90,No,2.2
932,933,NaN,28,NaN,NaN,73240,10.0,hr,2024-02-14,89.78,No,2.7
937,938,NaN,24,Unknown,HYD,40650,14.0,IT,2023-07-07,51.18,NaN,3.4
964,965,NaN,33,Unknown,Delhi,114185,-2.0,NaN,02-07-2022,98.44,No,1.9
979,980,NaN,32,F,Delhi,38904,0.0,HR,05-Jun-2021,76.78,N,3.5
987,42,NaN,58,Male,NaN,116517,3.0,hr,03-Sep-2018,42.47,Yes,3.2

In [264]:
# Q6. Fill missing values using appropriate techniques:
# • Name → "Unknown"
# • City → "Not Available"
# • Department → "Not Assigned"

# Fill missing values in Name
df["Name"] = df["Name"].fillna("Unknown")

In [265]:
# Fill missing values in City
df["City"] = df["City"].fillna("Not Available")

In [266]:
# Fill missing values in Department

df["Department"] = df["Department"].fillna("Not Assigned")

In [267]:
df.head(n = 55)

,Customer_ID,Name,Age,Gender,City,Salary,Experience,Department,Joining_Date,Performance_Score,Loan_Status,Rating
0,1,Amit,43,Female,Chennai,48886,26.0,Not Assigned,02/09/2022,90.81,N,4.5
1,2,Kiran,35,F,Bengaluru,"₹75,196",14.0,Not Assigned,04/01/2023,70.98,NaN,3.5
2,3,Neha,44,M,Not Available,111831,28.0,IT,23-Jun-2023,65.04,NaN,-2.0
3,79,Sneha,38,F,HYD,72973,3.0,HR,2021-01-04,65.51,no,1.4
4,5,Rohit,46,F,hyd,64961,17.0,hr,28/03/2018,98.68,Yes,12.0
5,6,Pooja,28,F,Delhi,38199,27.0,hr,19-Mar-2020,96.75,no,1.9
6,7,Neha,59,Female,Bangalore,31152,27.0,Not Assigned,31/12/2020,68.06,No,4.4
7,8,Unknown,22,M,Chennai,"₹58,457",5.0,it,2024-10-06,96.17,N,2.7
8,9,Pooja,-5,Unknown,Not Available,93372,5.0,Finance,07/12/2020,79.14,Yes,4.0
9,10,Kiran,58,F,Not Available,59378,17.0,IT,11-Apr-2020,98.43,Yes,2.5
10,11,Neha,56,M,hyd,81538,13.0,it,2021-04-19,42.72,yes,1.9
11,12,Anita,52,Female,Delhi,102686,28.0,IT,05-Sep-2021,63.25,NaN,1.4
12,13,Amit,29,Female,Mumbai,33324,14.0,hr,02-06-2021,89.12,yes,1.5
13,91,Neha,42,Unknown,Delhi,49384,5.0,it,20/12/2023,67.83,Yes,4.3
14,15,Rahul,20,NaN,Bangalore,97298,15.0,Finance,26-Feb-2018,70.05,yes,-2.0
15,16,Pooja,36,M,Bangalore,25508,9.0,IT,08-Jun-2020,60.17,Yes,1.2
16,17,Priya,29,Male,Chennai,110640,23.0,it,2020-01-16,74.57,N,3.2
17,18,Vijay,54,F,Pune,39779,9.0,HR,08/08/2020,81.22,NaN,2.5
18,19,Anita,20,Unknown,Not Available,53926,26.0,hr,14/02/2019,64.93,no,5.0
19,20,Rohit,22,NaN,Bengaluru,116802,5.0,Sales,23/05/2019,93.24,no,4.8
20,21,Arjun,39,Unknown,hyd,101983,21.0,Sales,12/11/2020,80.00,No,3.2
21,22,Vijay,59,Female,Hyderabad,40013,27.0,hr,2021-04-07,62.60,Y,2.9
22,23,Vijay,45,Male,Hyderabad,64791,14.0,IT,2021-05-07,63.78,Yes,-2.0
23,24,Ravi,25,F,Delhi,63379,2.0,Marketing,25/06/2020,75.77,Yes,3.9
24,25,Arjun,58,F,Pune,63771,-2.0,Not Assigned,2018-04-22,74.49,no,2.7
25,26,Unknown,35,Female,Hyderabad,NaN,12.0,hr,2020-06-11,88.03,N,1.0
26,71,Rohit,53,NaN,Mumbai,91146,11.0,it,07/08/2018,65.76,NaN,3.1
27,28,Arjun,34,Male,Delhi,98135,10.0,Marketing,2020-03-23,75.26,Y,2.8
28,29,Neha,27,M,Pune,99201,NaN,it,11-28-2018,65.90,Y,4.0
29,30,Vijay,49,Unknown,Pune,NaN,8.0,HR,2022-11-03,90.37,NaN,1.8
30,31,Vijay,28,F,Not Available,50238,22.0,Sales,09-15-2023,45.06,NaN,4.4
31,32,Priya,28,Unknown,Pune,28321,10.0,Finance,2024-07-17,75.04,yes,3.7
32,33,Rohit,53,F,hyd,90778,4.0,HR,05-05-2022,82.34,Yes,3.6
33,34,Kiran,34,Male,HYD,27928,29.0,Finance,08-30-2023,47.11,NaN,2.5
34,35,Ravi,23,Male,hyd,61309,9.0,it,09-Jun-2019,54.16,yes,3.2
35,36,Amit,30,Female,Bangalore,NaN,24.0,Finance,2023-09-29,NaN,Yes,3.5
36,79,Pooja,32,NaN,hyd,110730,28.0,it,2022-01-13,62.01,No,3.9
37,38,Priya,39,F,Bangalore,29240,25.0,Finance,2020-08-13,56.06,N,3.6
38,39,Anita,37,M,Mumbai,63004,6.0,Sales,2019-09-04,45.02,Y,4.8
39,40,Sneha,50,Unknown,HYD,69105,10.0,it,14/09/2018,91.66,No,3.7
40,41,Ravi,37,Unknown,Not Available,82768,18.0,Marketing,13/11/2020,96.78,Y,4.8
41,42,Arjun,45,Male,Pune,81014,23.0,HR,02-Apr-2024,43.50,Y,1.6
42,43,Sneha,34,F,Bangalore,55248,1.0,Marketing,2019-07-11,85.73,yes,1.9
43,44,Anita,35,F,Not Available,108549,29.0,Not Assigned,2019-11-02,46.92,No,2.6
44,45,Unknown,59,NaN,Mumbai,"₹117,161",25.0,HR,04-09-2018,93.75,N,4.0
45,46,Priya,25,Male,HYD,27431,18.0,HR,05-27-2021,NaN,No,4.9
46,47,Ravi,57,NaN,Delhi,98203,22.0,Finance,02/02/2018,97.51,N,1.9
47,48,Vijay,58,Male,HYD,104900,25.0,HR,2024-09-05,55.18,N,4.0
48,49,Vijay,38,F,HYD,53724,25.0,Marketing,13-Aug-2023,60.13,Yes,2.0
49,50,Rohit,33,Female,Pune,77898,9.0,IT,23-Jul-2023,69.60,yes,2.2
50,51,Sneha,58,Unknown,Bengaluru,96925,15.0,Sales,12-13-2021,52.14,yes,4.5
51,52,Rahul,35,M,Mumbai,34941,10.0,Not Assigned,03-27-2019,74.70,yes,4.4
52,53,Vijay,27,NaN,Bangalore,118814,14.0,hr,07-Apr-2019,78.46,NaN,3.1
53,54,Sneha,56,F,Bangalore,105744,16.0,it,14/05/2019,86.77,NaN,3.9
54,55,Sneha,41,NaN,Hyderabad,98503,13.0,Finance,04-01-2021,79.91,NaN,1.8

In [268]:
# Q7. Check whether duplicate rows exist.

df[df.duplicated()]

Empty DataFrame
Columns: [Customer_ID, Name, Age, Gender, City, Salary, Experience, Department, Joining_Date, Performance_Score, Loan_Status, Rating]
Index: []

In [269]:
# Q8. Find duplicate Customer_ID values and remove duplicate records while keeping the first occurrence.

# Display duplicate Customer_ID records
df[df.duplicated(subset="Customer_ID")]

,Customer_ID,Name,Age,Gender,City,Salary,Experience,Department,Joining_Date,Performance_Score,Loan_Status,Rating
36,79,Pooja,32,NaN,hyd,110730,28.0,it,2022-01-13,62.01,No,3.9
64,56,Rahul,24,F,Mumbai,118554,17.0,Sales,10-04-2022,57.40,NaN,3.7
70,71,Priya,29,Male,HYD,37953,7.0,Marketing,2019-02-26,68.09,Y,2.8
78,79,Pooja,54,Female,Mumbai,33403,26.0,IT,21-Aug-2022,90.90,N,2.6
90,91,Anita,22,Female,Delhi,NaN,26.0,hr,06-Jun-2023,53.49,Yes,1.1
127,61,Rahul,53,Female,Mumbai,79877,30.0,Finance,07-07-2018,64.97,yes,2.8
168,10,Rohit,25,M,Bengaluru,29225,7.0,it,10-20-2019,86.25,yes,4.1
187,72,Sneha,43,Female,Mumbai,57851,29.0,Sales,2019-09-13,97.50,Y,4.4
190,54,Sneha,20,Female,HYD,46243,7.0,it,29/11/2020,76.77,Yes,1.6
200,76,Pooja,21,F,Delhi,35046,23.0,HR,26/06/2022,99.32,yes,2.9
213,95,Pooja,35,Female,hyd,77031,29.0,IT,25-Aug-2023,60.16,N,2.9
235,25,Anita,22,Female,Bangalore,NaN,26.0,Sales,2021-10-12,89.65,NaN,-2.0
236,10,Ravi,59,Unknown,hyd,"₹94,274",12.0,Marketing,2023-05-07,53.24,Y,1.3
242,23,Sneha,33,Female,hyd,93548,12.0,Sales,2020-03-23,67.90,yes,2.9
252,26,Amit,50,Female,Pune,49624,18.0,it,2022-12-26,40.06,no,2.3
264,97,Rohit,46,M,Delhi,43860,4.0,Finance,2024-09-25,72.10,no,1.9
269,47,Arjun,33,Female,HYD,116978,15.0,it,08/09/2020,85.14,no,1.1
284,92,Priya,26,Male,Bengaluru,45923,9.0,HR,11-08-2023,NaN,Yes,2.7
286,60,Pooja,59,Unknown,Pune,103546,18.0,Finance,2019-08-13,47.54,no,3.0
288,69,Arjun,50,Female,Delhi,"₹100,214",22.0,it,11-Mar-2020,78.21,no,3.1
338,89,Amit,32,Unknown,hyd,NaN,25.0,IT,07/05/2018,90.44,Yes,1.3
342,21,Rahul,49,Male,Not Available,63577,29.0,it,09-Dec-2023,43.62,Yes,12.0
350,24,Neha,22,NaN,Pune,99311,8.0,it,13/08/2020,58.17,NaN,2.1
371,32,Kiran,47,Male,Bengaluru,60993,28.0,Sales,10-Nov-2022,57.02,No,2.9
379,66,Rohit,22,F,Not Available,49419,21.0,Sales,30-Jan-2021,-10.00,no,3.5
381,35,Unknown,49,F,Hyderabad,"₹115,289",12.0,Finance,2024-03-29,43.43,No,1.0
403,16,Anita,42,NaN,hyd,64590,20.0,IT,2018-05-30,51.08,Yes,4.9
404,35,Sneha,53,Female,Pune,95889,NaN,Marketing,2024-03-14,94.06,no,2.8
414,87,Amit,23,F,Delhi,75750,18.0,HR,06-Mar-2024,52.05,N,4.6
445,90,Rohit,55,Female,Not Available,105525,21.0,Marketing,08/11/2018,89.16,yes,3.8
457,22,Kiran,36,Male,Mumbai,82464,1.0,Not Assigned,2020-12-19,49.52,NaN,2.7
494,20,Arjun,21,M,Bangalore,89786,25.0,Finance,01/11/2018,73.66,NaN,12.0
498,50,Rohit,27,NaN,Delhi,"₹82,100",19.0,Not Assigned,26-Mar-2024,41.05,NaN,4.1
511,75,Rahul,38,Female,Pune,63842,28.0,hr,08/07/2021,40.35,Yes,1.5
519,100,Amit,29,Unknown,HYD,51632,22.0,IT,08-14-2023,95.18,Yes,4.8
532,59,Kiran,24,Unknown,Bangalore,91142,28.0,Marketing,2024-06-28,54.27,Y,3.0
547,5,Neha,36,F,hyd,84328,7.0,IT,15-Mar-2021,57.31,Y,2.4
549,53,Anita,25,M,HYD,53213,19.0,HR,20/04/2022,48.34,yes,1.3
576,40,Rohit,32,NaN,HYD,57915,15.0,IT,07/07/2023,64.02,NaN,2.4
578,70,Kiran,42,NaN,Pune,48738,3.0,it,29/07/2021,89.66,no,3.5
604,2,Sneha,23,F,hyd,87115,30.0,IT,01-05-2022,95.75,NaN,2.5
609,31,Kiran,48,Female,Mumbai,85151,19.0,it,10-21-2024,74.71,Y,2.4
628,89,Rahul,32,Unknown,Hyderabad,26837,12.0,hr,17/01/2022,65.18,Y,2.7
632,61,Ravi,60,NaN,Pune,63831,20.0,IT,10-23-2021,51.77,Yes,2.5
646,71,Pooja,27,F,Delhi,96331,3.0,IT,02-22-2019,69.48,yes,2.5
694,13,Ravi,44,M,Bengaluru,112966,18.0,Not Assigned,11-01-2021,88.18,yes,1.7
707,73,Priya,31,F,HYD,109946,8.0,HR,06-Nov-2018,63.30,Yes,3.9
709,67,Ravi,27,M,Pune,101546,26.0,Marketing,03-14-2024,91.47,Yes,2.8
738,62,Neha,48,Unknown,Chennai,46448,19.0,Marketing,05-05-2023,47.59,No,3.4
792,96,Priya,30,Male,Bangalore,64299,24.0,hr,06/04/2018,NaN,Yes,3.7
830,26,Rahul,23,Female,Chennai,47138,7.0,Finance,31/02/2024,40.82,No,1.9
855,99,Pooja,40,NaN,Mumbai,28296,NaN,hr,04-19-2023,83.37,Y,1.7
864,17,Anita,45,Female,Mumbai,107559,16.0,Finance,21-Nov-2023,63.67,yes,3.8
868,3,Rohit,30,M,Delhi,27581,29.0,Not Assigned,2019-03-14,44.94,NaN,2.9
916,89,Kiran,33,Unknown,Chennai,80763,27.0,it,14/03/2024,86.65,NaN,2.7
919,10,Priya,50,M,Bangalore,56299,3.0,Marketing,19-Feb-2020,45.37,yes,2.1
938,19,Pooja,49,Female,Hyderabad,64137,6.0,hr,2019-12-25,91.67,Yes,4.3
956,5,Pooja,30,F,Hyderabad,78654,28.0,Sales,25-Jun-2021,76.55,Yes,2.6
987,42,Unknown,58,Male,Not Available,116517,3.0,hr,03-Sep-2018,42.47,Yes,3.2
996,22,Amit,36,Male,Not Available,41273,27.0,hr,11-23-2022,65.87,NaN,1.5

In [270]:
# Remove duplicate Customer_ID records
df.drop_duplicates(subset="Customer_ID", keep="first", inplace=True)
df

,Customer_ID,Name,Age,Gender,City,Salary,Experience,Department,Joining_Date,Performance_Score,Loan_Status,Rating
0,1,Amit,43,Female,Chennai,48886,26.0,Not Assigned,02/09/2022,90.81,N,4.5
1,2,Kiran,35,F,Bengaluru,"₹75,196",14.0,Not Assigned,04/01/2023,70.98,NaN,3.5
2,3,Neha,44,M,Not Available,111831,28.0,IT,23-Jun-2023,65.04,NaN,-2.0
3,79,Sneha,38,F,HYD,72973,3.0,HR,2021-01-04,65.51,no,1.4
4,5,Rohit,46,F,hyd,64961,17.0,hr,28/03/2018,98.68,Yes,12.0
...,...,...,...,...,...,...,...,...,...,...,...,...
994,995,Ravi,50,Unknown,Hyderabad,113924,18.0,it,25/01/2021,82.53,Yes,2.3
995,996,Kiran,57,Male,Hyderabad,105886,12.0,IT,2019-08-15,40.16,no,4.3
997,998,Ravi,22,Unknown,Bangalore,85273,0.0,Sales,04-Mar-2023,50.90,Yes,1.6
998,999,Rohit,21,F,Mumbai,78945,13.0,hr,2021-11-16,61.89,No,3.8
999,1000,Rahul,52,Male,Chennai,66489,26.0,hr,05-Oct-2021,98.59,no,1.8

In [271]:
# Verify
print(df.duplicated(subset="Customer_ID").sum())

0

In [272]:
# Q9. Remove leading and trailing spaces from the Name column.

df["Name"] = df["Name"].str.strip()

In [273]:
# Q10. Standardize the Gender column into only:
# • Male
# • Female

df.replace({"Gender":{
    "male": "Male",
    "MALE": "Male",
    "M": "Male",
    "female": "Female",
    "FEMALE": "Female",
    "F": "Female"
}},inplace = True)

In [274]:
# Q11. Standardize city names.
# Example:
# HYD
# hyd
# Hyderabad
# ↓
# Hyderabad
# Do the same for Bengaluru/Bangalore if needed.

df.replace({"City": {
    "HYD":"Hyderabad",
    "hyd":"Hyderabad",
    "Hyderabad":"Hyderabad"
}},inplace = True)

In [275]:
df.replace({"City": {
    "Bengaluru":"Bengaluru",
    "Bangalore":"Bengaluru"
}},inplace = True)

In [276]:
df

,Customer_ID,Name,Age,Gender,City,Salary,Experience,Department,Joining_Date,Performance_Score,Loan_Status,Rating
0,1,Amit,43,Female,Chennai,48886,26.0,Not Assigned,02/09/2022,90.81,N,4.5
1,2,Kiran,35,Female,Bengaluru,"₹75,196",14.0,Not Assigned,04/01/2023,70.98,NaN,3.5
2,3,Neha,44,Male,Not Available,111831,28.0,IT,23-Jun-2023,65.04,NaN,-2.0
3,79,Sneha,38,Female,Hyderabad,72973,3.0,HR,2021-01-04,65.51,no,1.4
4,5,Rohit,46,Female,Hyderabad,64961,17.0,hr,28/03/2018,98.68,Yes,12.0
...,...,...,...,...,...,...,...,...,...,...,...,...
994,995,Ravi,50,Unknown,Hyderabad,113924,18.0,it,25/01/2021,82.53,Yes,2.3
995,996,Kiran,57,Male,Hyderabad,105886,12.0,IT,2019-08-15,40.16,no,4.3
997,998,Ravi,22,Unknown,Bengaluru,85273,0.0,Sales,04-Mar-2023,50.90,Yes,1.6
998,999,Rohit,21,Female,Mumbai,78945,13.0,hr,2021-11-16,61.89,No,3.8
999,1000,Rahul,52,Male,Chennai,66489,26.0,hr,05-Oct-2021,98.59,no,1.8

In [277]:
# Q12. Remove:
# • ₹ symbol
# • commas (,)
# Convert Salary into a numeric datatype.

df["Salary"] = df["Salary"].str.replace("₹", "")
df["Salary"] = df["Salary"].str.replace(",", "")
df["Salary"] = pd.to_numeric(df["Salary"])

In [278]:
df

,Customer_ID,Name,Age,Gender,City,Salary,Experience,Department,Joining_Date,Performance_Score,Loan_Status,Rating
0,1,Amit,43,Female,Chennai,48886.0,26.0,Not Assigned,02/09/2022,90.81,N,4.5
1,2,Kiran,35,Female,Bengaluru,75196.0,14.0,Not Assigned,04/01/2023,70.98,NaN,3.5
2,3,Neha,44,Male,Not Available,111831.0,28.0,IT,23-Jun-2023,65.04,NaN,-2.0
3,79,Sneha,38,Female,Hyderabad,72973.0,3.0,HR,2021-01-04,65.51,no,1.4
4,5,Rohit,46,Female,Hyderabad,64961.0,17.0,hr,28/03/2018,98.68,Yes,12.0
...,...,...,...,...,...,...,...,...,...,...,...,...
994,995,Ravi,50,Unknown,Hyderabad,113924.0,18.0,it,25/01/2021,82.53,Yes,2.3
995,996,Kiran,57,Male,Hyderabad,105886.0,12.0,IT,2019-08-15,40.16,no,4.3
997,998,Ravi,22,Unknown,Bengaluru,85273.0,0.0,Sales,04-Mar-2023,50.90,Yes,1.6
998,999,Rohit,21,Female,Mumbai,78945.0,13.0,hr,2021-11-16,61.89,No,3.8
999,1000,Rahul,52,Male,Chennai,66489.0,26.0,hr,05-Oct-2021,98.59,no,1.8

In [279]:
# Part 7: Data Type Conversion
# Q13. Convert:
# • Age
# • Salary
# • Experience
# • Performance_Score

# • Rating
# to proper numeric datatypes.

df["Age"] = pd.to_numeric(df["Age"], errors="coerce")

In [280]:
cols = ["Age", "Salary", "Experience", "Performance_Score", "Rating"]

df[cols] = df[cols].apply(pd.to_numeric)

In [281]:
df

,Customer_ID,Name,Age,Gender,City,Salary,Experience,Department,Joining_Date,Performance_Score,Loan_Status,Rating
0,1,Amit,43.0,Female,Chennai,48886.0,26.0,Not Assigned,02/09/2022,90.81,N,4.5
1,2,Kiran,35.0,Female,Bengaluru,75196.0,14.0,Not Assigned,04/01/2023,70.98,NaN,3.5
2,3,Neha,44.0,Male,Not Available,111831.0,28.0,IT,23-Jun-2023,65.04,NaN,-2.0
3,79,Sneha,38.0,Female,Hyderabad,72973.0,3.0,HR,2021-01-04,65.51,no,1.4
4,5,Rohit,46.0,Female,Hyderabad,64961.0,17.0,hr,28/03/2018,98.68,Yes,12.0
...,...,...,...,...,...,...,...,...,...,...,...,...
994,995,Ravi,50.0,Unknown,Hyderabad,113924.0,18.0,it,25/01/2021,82.53,Yes,2.3
995,996,Kiran,57.0,Male,Hyderabad,105886.0,12.0,IT,2019-08-15,40.16,no,4.3
997,998,Ravi,22.0,Unknown,Bengaluru,85273.0,0.0,Sales,04-Mar-2023,50.90,Yes,1.6
998,999,Rohit,21.0,Female,Mumbai,78945.0,13.0,hr,2021-11-16,61.89,No,3.8
999,1000,Rahul,52.0,Male,Chennai,66489.0,26.0,hr,05-Oct-2021,98.59,no,1.8

In [282]:
print(df.dtypes)

Customer_ID            int64
Name                  object
Age                  float64
Gender                object
City                  object
Salary               float64
Experience           float64
Department            object
Joining_Date          object
Performance_Score    float64
Loan_Status           object
Rating               float64
dtype: object

In [283]:
df["Salary"] = df["Salary"].astype("Int64")

In [284]:
df

,Customer_ID,Name,Age,Gender,City,Salary,Experience,Department,Joining_Date,Performance_Score,Loan_Status,Rating
0,1,Amit,43.0,Female,Chennai,48886,26.0,Not Assigned,02/09/2022,90.81,N,4.5
1,2,Kiran,35.0,Female,Bengaluru,75196,14.0,Not Assigned,04/01/2023,70.98,NaN,3.5
2,3,Neha,44.0,Male,Not Available,111831,28.0,IT,23-Jun-2023,65.04,NaN,-2.0
3,79,Sneha,38.0,Female,Hyderabad,72973,3.0,HR,2021-01-04,65.51,no,1.4
4,5,Rohit,46.0,Female,Hyderabad,64961,17.0,hr,28/03/2018,98.68,Yes,12.0
...,...,...,...,...,...,...,...,...,...,...,...,...
994,995,Ravi,50.0,Unknown,Hyderabad,113924,18.0,it,25/01/2021,82.53,Yes,2.3
995,996,Kiran,57.0,Male,Hyderabad,105886,12.0,IT,2019-08-15,40.16,no,4.3
997,998,Ravi,22.0,Unknown,Bengaluru,85273,0.0,Sales,04-Mar-2023,50.90,Yes,1.6
998,999,Rohit,21.0,Female,Mumbai,78945,13.0,hr,2021-11-16,61.89,No,3.8
999,1000,Rahul,52.0,Male,Chennai,66489,26.0,hr,05-Oct-2021,98.59,no,1.8

In [285]:
print(df.dtypes)

Customer_ID            int64
Name                  object
Age                  float64
Gender                object
City                  object
Salary                 Int64
Experience           float64
Department            object
Joining_Date          object
Performance_Score    float64
Loan_Status           object
Rating               float64
dtype: object

In [286]:
# Part 8: Invalid Values
# Q14. Find all rows where:
# • Age < 18
# • Age > 100
# Replace invalid ages with NaN.

df.loc[(df["Age"] < 18) | (df["Age"] > 100), "Age"] = pd.NA

In [287]:
df

,Customer_ID,Name,Age,Gender,City,Salary,Experience,Department,Joining_Date,Performance_Score,Loan_Status,Rating
0,1,Amit,43.0,Female,Chennai,48886,26.0,Not Assigned,02/09/2022,90.81,N,4.5
1,2,Kiran,35.0,Female,Bengaluru,75196,14.0,Not Assigned,04/01/2023,70.98,NaN,3.5
2,3,Neha,44.0,Male,Not Available,111831,28.0,IT,23-Jun-2023,65.04,NaN,-2.0
3,79,Sneha,38.0,Female,Hyderabad,72973,3.0,HR,2021-01-04,65.51,no,1.4
4,5,Rohit,46.0,Female,Hyderabad,64961,17.0,hr,28/03/2018,98.68,Yes,12.0
...,...,...,...,...,...,...,...,...,...,...,...,...
994,995,Ravi,50.0,Unknown,Hyderabad,113924,18.0,it,25/01/2021,82.53,Yes,2.3
995,996,Kiran,57.0,Male,Hyderabad,105886,12.0,IT,2019-08-15,40.16,no,4.3
997,998,Ravi,22.0,Unknown,Bengaluru,85273,0.0,Sales,04-Mar-2023,50.90,Yes,1.6
998,999,Rohit,21.0,Female,Mumbai,78945,13.0,hr,2021-11-16,61.89,No,3.8
999,1000,Rahul,52.0,Male,Chennai,66489,26.0,hr,05-Oct-2021,98.59,no,1.8

In [289]:
df.head(n = 55)

,Customer_ID,Name,Age,Gender,City,Salary,Experience,Department,Joining_Date,Performance_Score,Loan_Status,Rating
0,1,Amit,43.0,Female,Chennai,48886,26.0,Not Assigned,02/09/2022,90.81,N,4.5
1,2,Kiran,35.0,Female,Bengaluru,75196,14.0,Not Assigned,04/01/2023,70.98,NaN,3.5
2,3,Neha,44.0,Male,Not Available,111831,28.0,IT,23-Jun-2023,65.04,NaN,-2.0
3,79,Sneha,38.0,Female,Hyderabad,72973,3.0,HR,2021-01-04,65.51,no,1.4
4,5,Rohit,46.0,Female,Hyderabad,64961,17.0,hr,28/03/2018,98.68,Yes,12.0
5,6,Pooja,28.0,Female,Delhi,38199,27.0,hr,19-Mar-2020,96.75,no,1.9
6,7,Neha,59.0,Female,Bengaluru,31152,27.0,Not Assigned,31/12/2020,68.06,No,4.4
7,8,Unknown,22.0,Male,Chennai,58457,5.0,it,2024-10-06,96.17,N,2.7
8,9,Pooja,NaN,Unknown,Not Available,93372,5.0,Finance,07/12/2020,79.14,Yes,4.0
9,10,Kiran,58.0,Female,Not Available,59378,17.0,IT,11-Apr-2020,98.43,Yes,2.5
10,11,Neha,56.0,Male,Hyderabad,81538,13.0,it,2021-04-19,42.72,yes,1.9
11,12,Anita,52.0,Female,Delhi,102686,28.0,IT,05-Sep-2021,63.25,NaN,1.4
12,13,Amit,29.0,Female,Mumbai,33324,14.0,hr,02-06-2021,89.12,yes,1.5
13,91,Neha,42.0,Unknown,Delhi,49384,5.0,it,20/12/2023,67.83,Yes,4.3
14,15,Rahul,20.0,NaN,Bengaluru,97298,15.0,Finance,26-Feb-2018,70.05,yes,-2.0
15,16,Pooja,36.0,Male,Bengaluru,25508,9.0,IT,08-Jun-2020,60.17,Yes,1.2
16,17,Priya,29.0,Male,Chennai,110640,23.0,it,2020-01-16,74.57,N,3.2
17,18,Vijay,54.0,Female,Pune,39779,9.0,HR,08/08/2020,81.22,NaN,2.5
18,19,Anita,20.0,Unknown,Not Available,53926,26.0,hr,14/02/2019,64.93,no,5.0
19,20,Rohit,22.0,NaN,Bengaluru,116802,5.0,Sales,23/05/2019,93.24,no,4.8
20,21,Arjun,39.0,Unknown,Hyderabad,101983,21.0,Sales,12/11/2020,80.00,No,3.2
21,22,Vijay,59.0,Female,Hyderabad,40013,27.0,hr,2021-04-07,62.60,Y,2.9
22,23,Vijay,45.0,Male,Hyderabad,64791,14.0,IT,2021-05-07,63.78,Yes,-2.0
23,24,Ravi,25.0,Female,Delhi,63379,2.0,Marketing,25/06/2020,75.77,Yes,3.9
24,25,Arjun,58.0,Female,Pune,63771,-2.0,Not Assigned,2018-04-22,74.49,no,2.7
25,26,Unknown,35.0,Female,Hyderabad,<NA>,12.0,hr,2020-06-11,88.03,N,1.0
26,71,Rohit,53.0,NaN,Mumbai,91146,11.0,it,07/08/2018,65.76,NaN,3.1
27,28,Arjun,34.0,Male,Delhi,98135,10.0,Marketing,2020-03-23,75.26,Y,2.8
28,29,Neha,27.0,Male,Pune,99201,NaN,it,11-28-2018,65.90,Y,4.0
29,30,Vijay,49.0,Unknown,Pune,<NA>,8.0,HR,2022-11-03,90.37,NaN,1.8
30,31,Vijay,28.0,Female,Not Available,50238,22.0,Sales,09-15-2023,45.06,NaN,4.4
31,32,Priya,28.0,Unknown,Pune,28321,10.0,Finance,2024-07-17,75.04,yes,3.7
32,33,Rohit,53.0,Female,Hyderabad,90778,4.0,HR,05-05-2022,82.34,Yes,3.6
33,34,Kiran,34.0,Male,Hyderabad,27928,29.0,Finance,08-30-2023,47.11,NaN,2.5
34,35,Ravi,23.0,Male,Hyderabad,61309,9.0,it,09-Jun-2019,54.16,yes,3.2
35,36,Amit,30.0,Female,Bengaluru,<NA>,24.0,Finance,2023-09-29,NaN,Yes,3.5
37,38,Priya,39.0,Female,Bengaluru,29240,25.0,Finance,2020-08-13,56.06,N,3.6
38,39,Anita,37.0,Male,Mumbai,63004,6.0,Sales,2019-09-04,45.02,Y,4.8
39,40,Sneha,50.0,Unknown,Hyderabad,69105,10.0,it,14/09/2018,91.66,No,3.7
40,41,Ravi,37.0,Unknown,Not Available,82768,18.0,Marketing,13/11/2020,96.78,Y,4.8
41,42,Arjun,45.0,Male,Pune,81014,23.0,HR,02-Apr-2024,43.50,Y,1.6
42,43,Sneha,34.0,Female,Bengaluru,55248,1.0,Marketing,2019-07-11,85.73,yes,1.9
43,44,Anita,35.0,Female,Not Available,108549,29.0,Not Assigned,2019-11-02,46.92,No,2.6
44,45,Unknown,59.0,NaN,Mumbai,117161,25.0,HR,04-09-2018,93.75,N,4.0
45,46,Priya,25.0,Male,Hyderabad,27431,18.0,HR,05-27-2021,NaN,No,4.9
46,47,Ravi,57.0,NaN,Delhi,98203,22.0,Finance,02/02/2018,97.51,N,1.9
47,48,Vijay,58.0,Male,Hyderabad,104900,25.0,HR,2024-09-05,55.18,N,4.0
48,49,Vijay,38.0,Female,Hyderabad,53724,25.0,Marketing,13-Aug-2023,60.13,Yes,2.0
49,50,Rohit,33.0,Female,Pune,77898,9.0,IT,23-Jul-2023,69.60,yes,2.2
50,51,Sneha,58.0,Unknown,Bengaluru,96925,15.0,Sales,12-13-2021,52.14,yes,4.5
51,52,Rahul,35.0,Male,Mumbai,34941,10.0,Not Assigned,03-27-2019,74.70,yes,4.4
52,53,Vijay,27.0,NaN,Bengaluru,118814,14.0,hr,07-Apr-2019,78.46,NaN,3.1
53,54,Sneha,56.0,Female,Bengaluru,105744,16.0,it,14/05/2019,86.77,NaN,3.9
54,55,Sneha,41.0,NaN,Hyderabad,98503,13.0,Finance,04-01-2021,79.91,NaN,1.8
55,56,Priya,29.0,Unknown,Pune,88005,6.0,HR,07-05-2022,47.42,No,3.4